import express from "express";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import cors from "cors";
import mainRouter from "./routes/mainRouter.js";
dotenv.config();
connectDB();
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use("/", mainRouter);
app.listen(process.env.PORT, () => console.log("Server is running on PORT:" + process.env.PORT));
